---
output: html_document
author: Avinash Das Sahu
---
# this report test if the scRN gene clusters are predictive of ICB response in Genentech cohorts.
# response_information
```{r}
library(data.table)
source("/homes6/asahu/project/deeplearning/icb/deepImmune/source.R")
getwd()
icb.phenotype = fread("~/project/deeplearning/icb/data/Getz_scRNA/val_prediction.csv")
dataset.prefix = "Getz_scRNA"
icb.phenotype = icb.phenotype[unlist(icb.phenotype$sample_name) +1]
```
```{r}
load("~/project/deeplearning/icb/data/Getz_scRNA/phenotype_data.RData")
resp = fread("/liulab/asahu/data/ssgsea/xiaoman/getz/GSE120575_patient_ID_single_cells.txt", skip=19)
xx = paste0("V",1:35)
colnames(resp)[1:35] = xx
resp$V2 = gsub(resp$V2, pattern="-", replacement=".")
# resp.patient
resp.matched=resp[match(phenotype_sel.mod$patient.name, resp$V2)]
response = resp.matched$V6
response.bin = ifelse(response=="Responder", 1, 0)
```
## create tsnes 

```{r}
library(Rtsne)
library(ggplot2)
plotSNE <- function(data= data_tsne.merge,col = c(2:114),color.col = "condition",
                    title="t-SNE",size=0.25,do.discrete=T, filename=NULL, perplexity=30, theta=0.5, pca = FALSE, max_iter=5000, num_threads=32, tsne =NULL){
  set.seed(9)
  require(ggplot2)
  
  if(is.null(tsne)) tsne <- Rtsne(as.matrix(data[,col]), check_duplicates = FALSE, 
                                  pca = pca, perplexity=perplexity, theta=theta, dims=2, max_iter = max_iter, num_threads = num_threads)
  
  d_tsne_1 = as.data.frame(tsne$Y)
  d_tsne_1=cbind(d_tsne_1,data[,color.col,drop=F])
  
  ## plotting the results without clustering
  p=ggplot(d_tsne_1, aes(x=V1, y=V2)) +
    geom_point(size=size,aes_string(color=color.col), alpha=0.8) +
    guides(colour=guide_legend(override.aes=list(size=2))) +
    xlab("tSNE_1") + ylab("tSNE_2") +
    ggtitle(label = title) +
    theme_light(base_size=20) +
    theme(axis.text.x=element_blank(),
          axis.text.y=element_blank()) 
  if (do.discrete) {
    p<- p+ scale_colour_brewer(palette = "Set2")
  }
  ##theme(legend.position = "none")
  if(!is.null(filename)) ggsave(file=filename, p)
  list(tsne, p)
}

znorm = function(xx) (xx - mean(xx,na.rm=T))/sd(xx,na.rm=T)

plotSNE.array <- function(data= data_tsne.merge,col = c(2:114), color.cols = "condition",
                          title="t-SNE",size=0.25,do.discrete=T, filename=NULL, perplexity=30, theta=0.5, pca = FALSE, max_iter=5000, normalize=TRUE, num_threads=32){
  set.seed(9)
  
  tsne <- Rtsne(as.matrix(data[,col]), check_duplicates = FALSE, 
                pca = pca, perplexity=perplexity, theta=theta, dims=2, max_iter = max_iter, num_threads = num_threads)
  dt1 = as.data.frame(tsne$Y)
  ps = list()
  for (color.col in color.cols) {
    if(normalize) data[[color.col]] = znorm(data[[color.col]])
    d_tsne_1=cbind(dt1,col=data[[color.col]], shape=data$shape)
    
    
    
    title.curr = sprintf("%s_%s", title, color.col)
    
    ## plotting the results without clustering
    p=ggplot(d_tsne_1, aes(x=V1, y=V2)) +
      geom_point(size=size,aes(color=col, shape=as.factor(shape)), alpha=0.8) +
      scale_color_gradient2(low = "blue", mid = "white",
                            high = "red", space = "Lab" ) + 
      guides(colour=guide_legend(override.aes=list(size=2))) +
      xlab("tSNE_1") + ylab("tSNE_2") +
      ggtitle(label = title.curr) +
      theme_light(base_size=20) +
      theme(axis.text.x=element_blank(),
            axis.text.y=element_blank()) 
    if (do.discrete) {
      p<- p+ scale_colour_brewer(palette = "Set2")
    }
    ##theme(legend.position = "none")
    if(!is.null(filename)) {
      filename.curr = sprintf("%s_%s.pdf", filename, color.col)
      
      ggsave(file=filename.curr, p)
      ps[[color.col]]  = p
    }
  }
  list(d_tsne_1, ps)
}


color.clusters.features <- function(data, cluster,  color.cols = "condition",
                                    title="t-SNE",size=0.25,do.discrete=T, filename=NULL, normalize=TRUE){
  require(viridis)
  
  dt1 = as.data.frame(cluster)
  colnames(dt1) = c("V1", "V2")
  ps = list()
  for (color.col in color.cols) {
    if(normalize) data[[color.col]] = znorm(data[[color.col]])
    d_cluster_1=cbind(dt1,col=data[[color.col]], shape=data$shape)
    title.curr = sprintf("%s_%s", title, color.col)
    ## plotting the results without clustering
    p=ggplot(d_cluster_1, aes(x=V1, y=V2)) +
      geom_point(size=size,aes(color=col, shape=as.factor(shape)), alpha=0.7) +
      # scale_color_gradient2(low = "blue", mid = "white",
      # high = "red", space = "Lab" ) +
      
      # guides(colour=guide_legend(override.aes=list(size=2))) +
      xlab("Dim1") + ylab("Dim2") +
      ggtitle(label = title.curr) +
      theme_light(base_size=20) +
      theme(axis.text.x=element_blank(),
            axis.text.y=element_blank()) 
    if (do.discrete) {
      p<- p+ scale_colour_brewer(palette = "Set2")
    }else{
      # p <- p+  scale_color_viridis() 
      p <- p+ scale_color_gradientn(colours = heat.colors(20, alpha=0.7, rev=T))
      
    }
    ##theme(legend.position = "none")
    if(!is.null(filename)) {
      filename.curr = sprintf("%s_%s.pdf", filename, color.col)
      
      ggsave(file=filename.curr, p)
      ps[[color.col]]  = p
    }
  }
  ps
}


```
## Only use deepImmune embedding to get tsne ( **TODO** perhaps use umap to perform final cluster)
```{r}
tsne.dir = "/liulab/asahu/data/ssgsea/xiaoman/getz/tsnes/Monocyte_emb"
dir.create(tsne.dir)
loc=grep(pattern = ".output",colnames(icb.phenotype))
loc2=grep(pattern = "embedding",colnames(icb.phenotype))
d1=icb.phenotype[,c(loc,loc2),with=F]
d2 = resp.matched[,.(V2, V5, V6,V7)]
setnames(d2, 1:4,c("sample.name", "patient.name", "response", "treatment"))
d3 = phenotype_sel.mod[,.(assign.ident, CD274, PDCD1, oxphos.score)]
data_tsne.merge = as.data.frame(cbind(d3, d2, d1))

locx=which(data_tsne.merge$assign.ident=="Monocyte")
all.p = plotSNE(data = data_tsne.merge[locx,], col=58:121, size = 2,do.discrete=F, title="Monocyte Response",
    color.col = "response", perplexity = 30, theta = 0, pca=TRUE, 
    filename=sprintf("%s/%s_%s_final.pdf", tsne.dir, "Monocyte", "response"), max_iter=5000)

```
```{r}
print(all.p[[2]])
```
```{r}
load( "~/project/deeplearning/icb/data/Getz_scRNA/dataset_ssgsea_temp.RData")
load( "~/project/deeplearning/icb/data/Getz_scRNA/headers.RData")
icb.expression = t(dataset_ssgsea_temp[,2:16292, with=F])
colnames(icb.expression) =  dataset_ssgsea_temp$gene_name
rownames(icb.expression) =  gsub(unlist(headers[1])[-1], pattern="-", replacement=".")
phenotype_sel.mod$patient.name = gsub(phenotype_sel.mod$patient.name, pattern="-", replacement=".")
length(intersect(rownames(icb.expression), phenotype_sel.mod$patient.name))
icb.expression.matched = icb.expression[match(phenotype_sel.mod$patient.name, rownames(icb.expression)),]
icb.expression.matched = icb.expression[match(phenotype_sel.mod$patient.name, rownames(icb.expression)),]

```

```{r}
library(Seurat)
library(scater)
filename = "/liulab/asahu/data/ssgsea/xiaoman/getz/tsnes/Monocyte_emb/tsne_clustering.pdf"
data.tsne= as.data.frame(all.p[[1]]$Y)
data.exp = t(icb.expression.matched)
# # Defining clusters and markers:
library(scran)
data.DI = data_tsne.merge[locx,58:121]
# data.DI = data.tsne
snn.gr <- buildSNNGraph(t(data.DI))
data.tsne$clust1 = factor(igraph::cluster_walktrap(snn.gr)$membership)
data.tsne.dt = data.table(data.tsne)
data.summ = data.tsne.dt[,.(clust.m=median(V2)),by=clust1]
data.summ = data.summ[order(clust.m)]
data.summ$clust = seq(nrow(data.summ))
data.tsne$clust = as.factor(data.summ[match(data.tsne$clust1, clust1)]$clust)
p=ggplot(data.tsne, aes(x=V1, y=V2)) +
geom_point(size=2,aes(color=clust), alpha=0.8) +
guides(colour=guide_legend(override.aes=list(size=2))) +
xlab("Dim1") + ylab("Dim2") +
# ggtitle(label = title) +
theme_light(base_size=20) +
theme(axis.text.x=element_blank(),
  axis.text.y=element_blank()) 
# if(!is.null(filename)) ggsave(file=filename, p)
print(p)

```


## find marker genes 

```{r}
tpmMat, proj, min.c = 3, min.g = 200, max.g = 20000, org="hsa",
  normalization.method = NULL, do.scale = TRUE, do.center = FALSE, vars.to.regress = c("nUMI"),
  dims.use = 1:15, findMarkers = TRUE, marker.use = markers.CIBERSORT, res = 0.6

```


```{r}
SeuratPipeline <- function(tpmMat, proj, min.c = 3, min.g = 200, max.g = 20000, org="hsa",
  normalization.method = NULL, do.scale = TRUE, do.center = FALSE, vars.to.regress = c("nUMI"),
  dims.use = 1:15, findMarkers = TRUE, marker.use = markers.CIBERSORT, res = 0.6)
{
  #=========QC========
  message("Check gene and cell coverage ...")
  nGene = apply(tpmMat, 2, function(x) length(x[x>0]))
  nCell = apply(tpmMat, 1, function(x) length(x[x>0]))
  pdf(paste0(proj,"_QC_Coverage.pdf"),width=8,height=4.5)
  par(mfrow=c(1,2))
  plot(1:ncol(tpmMat),sort(nGene),pch=16,col="blue",ylab="Number of Genes Expressed",xlab="Cells",main="Cell Filter")
  abline(h=min.g,lwd=2,lty=2);text(ncol(tpmMat)/2,min.g+max(nGene)*0.05,paste0("n = ",min.g));legend("topleft",paste0("ave G = ",round(mean(nGene))),box.lty=0)
  plot(1:nrow(tpmMat),sort(nCell),pch=16,col="blue",ylab="Number of Cells Expressed",xlab="Genes",main="Gene Filter")
  abline(h=min.c,lwd=2,lty=2);text(nrow(tpmMat)/2,min.c+max(nCell)*0.05,paste0("n = ",min.c));legend("topleft",paste0("ave C = ",round(mean(nCell))),box.lty=0)
  dev.off()
  
  SeuratObj <- CreateSeuratObject(tpmMat, project = proj, min.cells = min.c, min.genes = min.g)
  if(org=="hsa"){
     mito.genes <- grep("^MT-", rownames(SeuratObj@data), value = TRUE)
     ercc.genes <- grep("^ERCC", rownames(SeuratObj@data), value = TRUE)}
  else{
     mito.genes <- grep("^mt-", rownames(SeuratObj@data), value = TRUE)
     ercc.genes <- grep("^ercc", rownames(SeuratObj@data), value = TRUE)}   
  percent.mito <- colSums(SeuratObj@data[mito.genes, ])/colSums(SeuratObj@data)
  percent.ercc <- colSums(SeuratObj@data[ercc.genes, ])/colSums(SeuratObj@data)
  SeuratObj <- AddMetaData(SeuratObj, percent.mito, "percent.mito")
  SeuratObj <- AddMetaData(SeuratObj, percent.ercc, "percent.ercc")
  p1<-VlnPlot(SeuratObj, c("percent.mito","percent.ercc"), nCol = 2)
  ggsave(file.path(paste0(proj,"_QC_Spikein.pdf")), p1, width = 6, height = 4.5)
  
  #=========Filter========
  message("Filter cells and find variable genes ...")  
  SeuratObj <- SubsetData(SeuratObj, subset.name = "percent.mito", accept.high = 0.05)
  SeuratObj <- SubsetData(SeuratObj, subset.name = "percent.ercc", accept.high = 0.05)
  SeuratObj <- FilterCells(object = SeuratObj, subset.names = c("nGene"),
               low.thresholds = min.g, high.thresholds = max.g) 
  
  SeuratObj <- NormalizeData(object = SeuratObj, normalization.method = normalization.method, scale.factor = 10000)
  SeuratObj <- FindVariableGenes(object = SeuratObj, mean.function = ExpMean, dispersion.function = LogVMR,
               x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5, do.plot = FALSE)
  if(do.scale) SeuratObj <- ScaleData(object = SeuratObj, vars.to.regress = vars.to.regress, do.center = do.center)
  
  #=========PCA===========
  message("PCA analysis ...")
  SeuratObj <- RunPCA(object = SeuratObj, pc.genes = SeuratObj@var.genes,
                        do.print = FALSE, rev.pca = TRUE)
  # VizPCA(object = SeuratObj, pcs.use = 1:2)
  # PCAPlot(object = SeuratObj, dim.1 = 1, dim.2 = 2)
  # PCHeatmap(object = SeuratObj, pc.use = 1:12, cells.use = 500, do.balanced = TRUE,
  #           label.columns = FALSE, use.full = FALSE)
  # SeuratObj <- JackStraw(object = SeuratObj, num.replicate = 100, display.progress = FALSE)
  # JackStrawPlot(object = SeuratObj, PCs = 1:12)
  p2 = PCElbowPlot(object = SeuratObj )
  ggsave(file.path(paste0(proj,"_PCElbowPlot.pdf")), p2, width = 5, height = 4)
  
  #=========tSNE===========
  message("t-SNE analysis ...")
  SeuratObj <- FindClusters(object = SeuratObj, reduction.type = "pca", dims.use = dims.use,
						    resolution = res, print.output = 0, save.SNN = TRUE)
  SeuratObj <- RunTSNE(object = SeuratObj, dims.use = dims.use, do.fast = TRUE)
  pdf(file.path(paste0("tSNE_origIdent_", SeuratObj@project.name, "_cluster.pdf")),width=5, height=4)
  TSNEPlot(object = SeuratObj, do.label = TRUE, pt.size = 0.5, group.by = paste0("res.",res))
  dev.off()
  pdf(file.path(paste0("tSNE_origIdent_", SeuratObj@project.name, "_primary.pdf")), width=5, height=4)
  TSNEPlot(object = SeuratObj, do.label = TRUE, pt.size = 0.5, group.by = "orig.ident")
  dev.off()

  #=========identify marker===========
  cluster.markers <- NULL
  if (findMarkers){
  message("Find marker genes and annotation ...")
  cluster.markers <- FindAllMarkers(object = SeuratObj, only.pos = TRUE, min.pct = 0.1)
  cluster.markers <- cluster.markers[cluster.markers$p_val_adj<0.000001, ]
  
  current.cluster.ids = as.integer(levels(cluster.markers$cluster))
  new.cluster.ids = AssignCellTypeSeurat(cluster.markers, marker.use)
  SeuratObj@meta.data$assign.ident = SeuratObj@ident[rownames(SeuratObj@meta.data)]
  SeuratObj@meta.data$assign.ident = plyr::mapvalues(x = SeuratObj@meta.data$assign.ident,
 											 from = current.cluster.ids, to = new.cluster.ids)
  pdf(file.path(paste0("tSNE_assignIdent_", SeuratObj@project.name, "_annotated.pdf")), width=6, height=4)
  TSNEPlot(object = SeuratObj, do.label = TRUE, pt.size = 0.5, group.by = "assign.ident")
  dev.off()}
  
  saveRDS(cluster.markers, file.path(paste0(proj, "_DiffMarkers.rds")))
  saveRDS(SeuratObj, file.path(paste0(proj, "_SeuratObj.rds")))
  return(list(SeuratObj = SeuratObj, markers = cluster.markers))
}

```
```{r}
proj="/liulab/asahu/data/ssgsea/xiaoman/getz/tsnes/Monocyte_emb/Pagoda";
dir.create(proj)
proj; min.c = 3; min.g = 200; nPCs = 100; nKs = 30
#=========QC========
message("Check gene and cell coverage ...")
nGene = apply(tpmMat, 2, function(x) length(x[x>0]))
tpmMat = t(tpmMat)
library(pagoda2)
tpmMat = t(icb.expression.matched[locx,]);
tpmMat = Matrix(tpmMat)
proj="/liulab/asahu/data/ssgsea/xiaoman/getz/tsnes/Monocyte_emb/Pagoda";
nGene = apply(tpmMat, 2, function(x) length(x[x>0]))
nGene = apply(tpmMat, 2, function(x) length(x[x>0]))
nCell = apply(tpmMat, 1, function(x) length(x[x>0]))
# genes x cells matrix
cm = tpmMat
par(mfrow=c(1,2), mar = c(3.5,3.5,2.0,0.5), mgp = c(2,0.65,0), cex = 1.0)
hist(log10(colSums(cm)+1),main='molecules per cell',col='cornsilk',xlab='log10(molecules per cell)')
counts <- gene.vs.molecule.cell.filter(cm,min.cell.size=500)
hist(log10(rowSums(counts)+1),main='Molecules per gene',xlab='molecules (log10)',col='cornsilk')
abline(v=1,lty=2,col=2)
hist(log10(rowSums(counts)+1),main='Molecules per gene',xlab='molecules (log10)',col='cornsilk')
# abline(v=1,lty=2,col=2)
counts <- counts[rowSums(counts)>=5,]
rownames(counts) <- make.unique(rownames(counts))
r <- Pagoda2$new(counts,log.scale=TRUE, n.cores=2)
r <- Pagoda2$new(counts,log.scale=TRUE, n.cores=16)
r$adjustVariance(plot=T,gam.k=10)
r$calculatePcaReduction(nPcs=nPCs,n.odgenes=3e3,maxit=1000)

```


```{r}
PipelinePagoda <- function(tpmMat, proj, min.c = 3, min.g = 200, nPCs = 100, nKs = 30)
{
  library(pagoda2)

  #=========QC========
  message("Check gene and cell coverage ...")
  nGene = apply(tpmMat, 2, function(x) length(x[x>0]))
  nCell = apply(tpmMat, 1, function(x) length(x[x>0]))
  pdf(paste0(proj,"_QC_Coverage.pdf"),width=8,height=4.5)
  par(mfrow=c(1,2))
  plot(1:ncol(tpmMat),sort(nGene),pch=16,col="blue",ylab="Number of Genes Expressed",xlab="Cells",main="Cell Filter")
  abline(h=min.g,lwd=2,lty=2);text(ncol(tpmMat)/2,min.g+max(nGene)*0.05,paste0("n = ",min.g));legend("topleft",paste0("ave G = ",round(mean(nGene))),box.lty=0)
  plot(1:nrow(tpmMat),sort(nCell),pch=16,col="blue",ylab="Number of Cells Expressed",xlab="Genes",main="Gene Filter")
  abline(h=min.c,lwd=2,lty=2);text(nrow(tpmMat)/2,min.c+max(nCell)*0.05,paste0("n = ",min.c));legend("topleft",paste0("ave C = ",round(mean(nCell))),box.lty=0)
  dev.off()

  #=========PCA & tSNE=======
  message("Filter cells, variance shrinkage, PCA and tSNE analysis ...")
  tpmMat <- tpmMat[!duplicated(rownames(tpmMat)),]
  r <- Pagoda2$new(tpmMat,modelType='plain',trim=10,log.scale=T)
  r$adjustVariance(plot=T,do.par=T,gam.k=10)
  r$calculatePcaReduction(nPcs=nPCs,n.odgenes=3e3,maxit=1000)
  r$makeKnnGraph(k=nKs,type='PCA',center=T,distance='cosine');
  require(igraph)
  r$getKnnClusters(method=multilevel.community,type='PCA',name='multilevel')
  r$getEmbedding(type='PCA',embeddingType='tSNE',perplexity=50,verbose=T)
  png(file.path(paste0("tSNE_origIdent_", proj, "_cluster.png")),res=300, width=4, height=4, units = "in")
  r$plotEmbedding(type='PCA',embeddingType='tSNE',show.legend=F,mark.clusters=T,min.group.size=10,shuffle.colors=F,mark.cluster.cex=1,alpha=0.3,main=proj)
  dev.off()
 
  #=========identify marker===========
  message("Find marker genes ...")
  deSets <- get.de.geneset(r, groups = r$clusters$PCA[[1]], prefix = 'de_')
  saveRDS(deSets, file.path(paste0(proj, "_Pagoda_DiffMarkers.rds")))
  
  CellType <- AssignCellTypePagoda(deSets)
  r$clusters$PCA$annotation <- r$clusters$PCA$multilevel
  r$clusters$PCA$multilevel <- plyr::mapvalues(x = r$clusters$PCA$multilevel,
 										 from = levels(r$clusters$PCA$multilevel), to = CellType)
  png(file.path(paste0("tSNE_origIdent_", proj, "_annotated.png")),res=300, width=4, height=4, units = "in")
  r$plotEmbedding(type='PCA',embeddingType='tSNE',show.legend=F,mark.clusters=T,min.group.size=10,shuffle.colors=F,mark.cluster.cex=1,alpha=0.3,main=proj)
  dev.off() 
  
  saveRDS(r, file.path(paste0(proj, "_PagodaObj.rds")))
  return(list(PagodaObj=r, markers = deSets))
}





```


```{r}
library(scater)
monocyte.exp  = data.exp[,locx]
sce = SingleCellExperiment(
    assays = list(counts = monocyte.exp))
ave.counts <- rowMeans(counts(sce))
keep <- rowMeans(counts(sce)) >= 0.2
sum(keep)
sce1 = sce[keep, ]
sce1 = normalize(sce1)
```



