---
title: "Personalization check correlation"
output: html_notebook
---


## expression association 

```{r}
deepimmune.out = fread("~/project/deeplearning/icb/data/tcga/citokines.v1/tensorboardLog/20190924-011458/best_val_0.csv")
deepimmune.out.col = colnames(deepimmune.out)
inp.col = deepimmune.out.col[10:136]
dat= deepimmune.out[,inp.col, with=F]

xx = cor(dat, method = "spearman", use = "pairwise.complete.obs"); xx[is.na(xx)] = 0
hc = hclust(as.dist(1 - abs(xx)), method = "complete")
M = xx[order.dendrogram(as.dendrogram(hc)), order.dendrogram(as.dendrogram(hc))]
xx = cor(t(dat), method = "spearman", use = "pairwise.complete.obs"); xx[is.na(xx)] = 0
hr = hclust(as.dist(1 - abs(xx)), method = "complete")

library(corrplot)
corrplot(M, method = "circle", tl.cex=.4)

dat.out= deepimmune.out[,paste0(inp.col,".output"), with=F]
setnames(dat.out, seq_along(inp.col), inp.col)
xx = cor(dat.out, method = "spearman", use = "pairwise.complete.obs"); xx[is.na(xx)] = 0
M1 = xx[order.dendrogram(as.dendrogram(hc)), order.dendrogram(as.dendrogram(hc))]
corrplot(M1, method = "circle", tl.cex=.4)

    library(ComplexHeatmap)
    Heatmap(dat, name = name, column_title = "Variables", row_title = "Samples", 
        row_names_gp = gpar(fontsize = 7))
    
require(heatmap3)
 heatmap3(dat, Rowv = as.dendrogram(hr), Colv = as.dendrogram(hc), 
        scale = "col", balanceColor = T, showRowDendro = F, showColDendro = F, 
        cexRow = 0.5, cexCol = 0.5)

```


```{r}
cwd =  "/liulab/asahu/projects/icb/data/tcga/citokines.v1/tensorboardLog/20190924-011458/personalization"
common.model = fread("/liulab/asahu/projects/icb/data/tcga/citokines.v1/tensorboardLog/20190924-011458//best_val_0.csv")
ifs = grep(pattern="output", colnames(common.model), value=T)
out = lapply( seq(139), function(ii) {
    if.curr = ifs[[ii]]
    curr.dir = list.files(path=cwd, full.names = T, recursive = F, pattern = sprintf("if_%s_", ii))
    aa = fread(sprintf("%s/best_val_0.csv",curr.dir))
    aa[[if.curr]]
})
out.dt = data.table(do.call(cbind, out))
colnames(out.dt) = ifs

dat.out.person= deepimmune.out[,paste0(inp.col,".output"), with=F]

xx = cor(dat.out.person, method = "spearman", use = "pairwise.complete.obs"); xx[is.na(xx)] = 0
M1 = xx[order.dendrogram(as.dendrogram(hc)), order.dendrogram(as.dendrogram(hc))]
corrplot(M1, method = "circle", tl.cex=.4)


```


## Prediction in genentech cohort across subtypes. 

```{r}
library(DESeq2) 
load("/liulab/asahu/data/ssgsea/xiaoman/Genentech/genentech_cds.RData") # data name is cds
genentech.exp = counts(cds)
genentech.feat = fData(cds)
genentech.pheno = pData(cds)
genentech.tpm = fread("/liulab/asahu/data/ssgsea/xiaoman/Genetech_expression_TPM.txt")
genetech.tpm.mat=as.matrix(t(genentech.tpm[,-1,with=F]))
colnames(genetech.tpm.mat)=genentech.tpm$V1
genetech.tpm.mat=genetech.tpm.mat[rownames(genentech.pheno),]

```



## genentech cohort for testing 

```{r}

datasets.tcga = fread("~/project/deeplearning/icb/data/tcga/citokines.v1/dataset.txt") 

ref.expression.cancertype = as.matrix(datasets.tcga[cancertype=="BLCA",2:1345,with=F] )
dataset_ssgsea_sel = genetech.tpm.mat[,colnames(ref.expression.cancertype)]
dataset_ssgsea_matched = match.expression.distribution(dataset_ssgsea_sel, ref.expression.cancertype)

if(F){
    phenotype_sel.mod = phenotype_sel
    phenotype_sel.mod[, Response:=as.double(Response)]
    phenotype_sel.mod[is.na(Response) & (vital_status == 1) & (survive < 3)]$Response = 0
    phenotype_sel.mod[is.na(Response) & (survive > 7)]$Response = 1
    dataset_ssgsea_sel = dataset_ssgsea_sel
    phenotype_order[length(phenotype_order)] = "Response" # last is response
    phenotype_mat =  phenotype_sel.mod
    temp = setdiff(phenotype_order, colnames(phenotype_mat))
    temp.mat = matrix(NA, ncol=length(temp), nrow=nrow(phenotype_mat))
    colnames(temp.mat) =temp
    phenotype_mat = cbind(phenotype_mat, temp.mat)
    phenotype.ext.mat = phenotype_mat[,match(phenotype_order, colnames(phenotype_mat)),with=F ]
}



# neoantigen.pheno
neoantigen.pheno.inx = colnames(datasets.tcga)[1346:1540]
neoantigen.pheno = matrix(NA, nrow=nrow(dataset_ssgsea_matched), ncol = length(neoantigen.pheno.inx))
colnames(neoantigen.pheno) = neoantigen.pheno.inx
neoantigen.pheno[,"Silent.Mutation.Rate"] = genentech.pheno$`FMOne mutation burden per`
neoantigen.pheno[,"SNV.Neoantigens"] = genentech.pheno$`Neoantigen burden per MB`
neoantigen.pheno[,"OS.time"] = genentech.pheno$`os`
neoantigen.pheno[,"OS.filtered"] = genentech.pheno$`censOS`
genetech.dataset = cbind(cancertype="BLCA", dataset_ssgsea_matched, neoantigen.pheno)
```


```{r}
source("/homes6/asahu/project/deeplearning/icb/deepImmune/data_processing/ssgsea/imputation/scRNA/epoch-142/source.proj.R")

output.dir = "~/project/deeplearning/icb/data/genentech.tpm/citokines.v1/"
write.dataset(output.dir = output.dir, dataset = genetech.dataset, sample.name = rownames(genetech.dataset))
file.copy("~/project/deeplearning/icb/data/tcga/citokines.v1/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/citokines.v1/datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/citokines.v1/datasets_test_list.txt", output.dir)

dataset.new.col = colnames(genetech.dataset)
monitored.mutation = c("ARID1A", "ARID1B", "SMARCA4",  "STK11", "B2M", "PTEN", "PTPN2", "APLNR")
which( dataset.new.col %in%  paste0(monitored.mutation, ".mut")) -2 
length(input.output.genes) + 4
length(input.output.genes) + 4 + dim(if.data)[2] + dim(protien.data)[2]  + length(monitored.mutation)
```

## Evaluate all signatures for ICB response on all genentech-subtypes

```{r}
source("/homes6/asahu/project/deeplearning/icb/deepImmune/source.R")
source('~/project/deeplearning/icb/deepImmune/data_processing/ssgsea/imputation/scRNA/epoch-142/source.proj.R')
cwd= "~/project/deeplearning/icb/data/tcga/citokines.v1/tensorboardLog/20190924-011458/best_model/"
# heatmap 
icb.data = read.deepImmune.output(deepImmune.dir = "~/project/deeplearning/icb/data/genentech.tpm/citokines.v1", 
                       cwd =cwd, 
                       copy.deepImmune.output=T
                       )


```

```{r, echo=F}
cal.aucs <- function(resp, signature.mat) {
    require()
    temp = apply(signature.mat, 2, function(xx) {
        tryCatch( pROC::auc(response=resp, predictor=xx),
                 error= function(e) NA)
    })
    unlist(temp)
}

```

## on specific subtypes run auc of signatures 
```{r}
signatures =  icb.data$icb.phenotype[match(rownames(genentech.pheno), icb.data$dataset.sample.name),c(49:50,145:347),with=F]
response = genentech.pheno$binaryResponse
index.pheno = c(3:6, 10, 11, 13, 15, 16, 23:25)

pheno.out = list()
for (ii in index.pheno) {
    pheno.curr = genentech.pheno[[ii]]
    tab = table(pheno.curr)
    tab = tab[tab > 10]
    if(length(tab) > 0)
    for(tt in seq_along(tab)){
        name.curr = sprintf("%s.%s", colnames(genentech.pheno)[ii], names(tab)[tt])
        inx.curr = which( pheno.curr == names(tab)[tt])
        if(length(inx.curr) > 10)
            pheno.out[[name.curr]] = cal.aucs(response[inx.curr], signatures[inx.curr,])
    }
    
}

pheno.out.mat = do.call(rbind, pheno.out)

colnames(pheno.out.mat)[which(pheno.out.mat > 0.9,arr.ind = T)[,2]]
pheno.out.mat[is.na(pheno.out.mat)] = 0.5
pheno.out.mat = abs(pheno.out.mat - 0.5) + 0.5 

library(ComplexHeatmap)
Heatmap(pheno.out.mat, 
        name = "Predictive Power", #title of legend
        column_title = "Subtype", row_title = "Signature",
        row_order = NULL,
         show_column_dend = FALSE,
         show_row_dend = FALSE,
        row_names_gp = gpar(fontsize = 6), # Text size for row names
        column_names_gp = gpar(fontsize = 5) # Text size for row names
)

# dev.off()
```


## Don't know what this does

```{r , eval=F, echo=T}
library(ggplot2)
library(ggthemes)
# Barplot
# intersect(colnames(data.curr), colnames(genentech.pheno))
data.curr = cbind(data.curr, genentech.pheno[colnames(sco.curr),])

bp<- ggplot(data.curr, aes(x=data.curr$`Immune phenotype`, y=as.factor(cluster), fill=group))+
geom_bar(width = 1, stat = "identity")
bp

myplot <- data.curr[!is.na(Lund2)] %>% ggplot(. , aes(Lund2, group = cluster, fill = cluster)) + 
          # geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
          geom_bar(aes(y = ..prop..), stat="count",position=position_dodge()) + 
          scale_y_continuous(labels=scales::percent) +
          ylab("relative frequencies") 
          # facet_grid(~cluster)
          # facet_grid(~data.curr$`Immune phenotype`)

avi.dt = cbind( data.curr[,.(cluster)], genentech.pheno[colnames(sco.curr), colnames(genentech.pheno)[-c(18:22)]])
avi.dt1 = melt(avi.dt,1)
avi.dt1 = avi.dt1[!is.na(value)][(value!="NE")]

myplot <- ggplot(avi.dt1 , aes(value, group = interaction(cluster, variable), fill = cluster)) + 
          # geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
          geom_bar(aes(y = ..prop..), stat="count",position=position_dodge()) + 
          scale_y_continuous(labels=scales::percent) +
          ylab("relative frequencies") +
        facet_wrap(~variable, scales = "free", ncol=5)
myplot
```


