---
title: "Oxphos RNA-seq data"
output: html_notebook
---


```{r}
aa = readxl::read_excel("/liulab/xmwang/oxphos_proj/loading_data/ERRa_RNAseq_SKBR3_all-reads_norm.xlsx")

bb = as.matrix(aa[,13:56])
# bb = which(!grepl("/", colnames(bb)))
tpm.mat = lapply(which(!grepl("/", colnames(bb))), function(tt) readcount2tpm(count = bb[[tt]], aa$Size))
tpm.mat = do.call(cbind, tpm.mat)
rownames(tpm.mat) = aa$`Gene symbol`
```

```{r}

#' Create function of automatically caclulate PC
#'
#' @param dataset_ssgsea_sel Expression matrix
#' @param ref.expression.RData 
#' @param ref.expression.RData 
#' @param cancer.type if any cancer type. Default (NULL) uses all reference.
#' @param len_selected Number of PCs 
#' @param pca_obj.RData Default is NULL so it will reestiamte the PCS. 
#'
#' @return
#' @export
#'
#' @examples
get.pc1 = function(dataset_ssgsea_sel, ref.expression.RData, ref.cancertype.RData = NULL, cancer.type=NULL, len_selected =50, pca_obj.RData = NULL){
    require(avinash)
    if(is.null(pca_obj.RData)){
        pca.obj = NULL
    }else{
        load(pca_obj.RData)
    }
    dataset_ssgsea_norm = normalize.expression(dataset_ssgsea_sel)
    load(ref.expression.RData)
    if(!is.null(ref.cancertype.RData)) load(ref.cancertype.RData)
    
    dataset_ssgsea_sel = dataset_ssgsea_sel[,colnames(ref.expression)]
    stopifnot(identical(colnames(dataset_ssgsea_sel), colnames(ref.expression)))
    if(!is.null(cancer.type)) ref.expression = ref.expression[ref.cancertype ==cancer.type, ]
    dataset_ssgsea_sel = match.expression.distribution(dataset_ssgsea_sel, ref.expression)
    temp_out = get_pca(dataset_ssgsea_sel, pca_obj = pca_obj, scale=F) 
    pca_obj = temp_out$pca_obj
    pca_obj$len_selected = len_selected
    temp_out$pca_out[,seq(pca_obj$len_selected)]
}

```
### Create function of automatically caclulate PC

```{r}

match.expression.distribution_col = function(exp, ref.exp){
	require(parallel)
	out = do.call(rbind, mclapply(seq(nrow(exp)), function(tt) match.distribution.zeros(exp[tt,], ref.exp[,tt]), mc.cores=32))
	rownames(out) =rownames(exp)
	colnames(out) =colnames(exp)
	out 

}

#' Create function of automatically caclulate PC
#'
#' @param dataset_ssgsea_sel Expression matrix
#' @param ref.expression.RData 
#' @param ref.expression.RData 
#' @param cancer.type if any cancer type. Default (NULL) uses all reference.
#' @param len_selected Number of PCs 
#' @param pca_obj.RData Default is NULL so it will reestiamte the PCS. 
#'
#' @return
#' @export
#'
#' @examples
get.pc1 = function(dataset_ssgsea_sel, ref.expression.RData, ref.cancertype.RData = NULL, cancer.type=NULL, len_selected =50, pca_obj.RData = NULL){
    require(avinash)
    if(is.null(pca_obj.RData)){
        pca.obj = NULL
    }else{
        load(pca_obj.RData)
    }
    dataset_ssgsea_norm = normalize.expression(dataset_ssgsea_sel)
    load(ref.expression.RData)
    if(!is.null(ref.cancertype.RData)) load(ref.cancertype.RData)
    
    dataset_ssgsea_sel = dataset_ssgsea_sel[,colnames(ref.expression)]
    stopifnot(identical(colnames(dataset_ssgsea_sel), colnames(ref.expression)))
    if(!is.null(cancer.type)) ref.expression = ref.expression[ref.cancertype ==cancer.type, ]
    dataset_ssgsea_sel = match.expression.distribution_col(dataset_ssgsea_sel, ref.expression)
    temp_out = get_pca(dataset_ssgsea_sel, pca_obj = pca_obj, scale=F) 
    pca_obj = temp_out$pca_obj
    pca_obj$len_selected = len_selected
    temp_out$pca_out[,seq(pca_obj$len_selected)]
}

```


```{r}

#' Title
#'
#' @param common.genes common genes to imputed 
#' @param incomplete_exp_mat incomplete expression matrix sample x genes
#' @param ref  reference expression matrix sample x genes
#'
#' @return
#' @export
#'
#' @examples
impute.closest.gene = function(common.genes, incomplete_exp_mat, ref= NULL, subsample=NULL){
    na.genes = colSums(is.na(incomplete_exp_mat)) > 0  
    na.names = colnames(incomplete_exp_mat)[na.genes]
    gene1 = colnames(incomplete_exp_mat)[!na.genes]
    
    genes.imputed = setdiff(common.genes, gene1)
    na.names = intersect(na.genes, common.genes)
    
    if(length(genes.imputed) > 0) {
        if(is.null(class(ref))){
            ref.dt = fread("/liulab/asahu/data/ssgsea/xiaoman/Genetech_expression_TPM.txt")
            ref = t(as.matrix(ref.dt[,seq(2,ncol(ref.dt)),with=F]))
            setnames(ref.dt, 1, "gene_name")
            colnames(ref ) = ref.dt$gene_name
        }
        ref.dt.gene_name = colnames(ref)
        if (!is.null(subsample)) {
            ref = ref[sample.int(nrow(ref), size=nrow(ref)*subsample),]
        }
        impute = ref[,genes.imputed, drop=F]
        only.genes = intersect(gene1, ref.dt.gene_name)
        incomplete_exp_mat1 = incomplete_exp_mat[,only.genes, drop=F]
        exp.present = ref[,only.genes,drop=F]
        cors = WGCNA::bicor(impute, exp.present, use="pairwise.complete.obs")
        # cors = pcor(impute, exp.present, use="pairwise.complete.obs")
        genes.inx = apply(cors,1, 
                          function(tt) ifelse(sum(!is.na(tt)), which.max(tt), NA)
        )
        
        imputed = incomplete_exp_mat1[,genes.inx, drop=F]
        imputed[is.na(imputed)] = 0
        colnames(imputed) = genes.imputed
        for(ii in which(na.genes)){
            col.inx = colnames(incomplete_exp_mat)[ii]
            imputed[,col.inx] = ifelse(is.na(incomplete_exp_mat[,ii]), imputed[,col.inx], incomplete_exp_mat[,ii])
        }
        merged = cbind(incomplete_exp_mat1, imputed) 
        incomplete_exp_mat = merged
    }
    incomplete_exp_mat[,common.genes]
}
```



## remember there are two different ref expression one for impute and other pc. 
```{r}
load("/liulab/asahu/data/ssgsea/xiaoman/getz/all.tcga.genes.RData")
common.genes = all.tcga.genes
dataset_ssgsea_mat = t(tpm.mat)

load("~/project/deeplearning/icb/data/tcga/scrna.v4.pcs/ref.expression.norm.RData")
dataset_ssgsea_mat1 = impute.closest.gene(common.genes,dataset_ssgsea_mat, ref =ref.expression.norm, subsample = .02) ## this is from avinash library
dataset_ssgsea_mat = dataset_ssgsea_mat1[ ,common.genes] 
stopifnot(any(!is.na(dataset_ssgsea_mat)))

dataset_ssgsea_sel = dataset_ssgsea_mat
general.pcs = get.pc1(dataset_ssgsea_sel, 
                      ref.expression.RData = "~/project/deeplearning/icb/data/tcga/scrna.v1/ref.expression.RData",
                      ref.cancertype.RData = "~/project/deeplearning/icb/data/tcga/scrna.v1/ref.cancertype.RData",
                      pca_obj.RData = "~/project/deeplearning/icb/data/tcga/scrna.v1//pca_obj.RData"
)
```
##  Expression inputs
```{r}

dataset_ssgsea_sel.norm = normalize.expression(dataset_ssgsea_sel, num.samp.thr = 0) 

dataset_ssgsea_sel.norm = match.expression.distribution_col(dataset_ssgsea_sel.norm, ref.exp = ref.expression.norm)

pc.data = data.table(cbind(cancertype="CELLLINE", general.pcs))
extra.genes.inx = c("TGFB1", "TGFBR2", "KLRC1")
top.genes.extra = c("PMS2", "MSH6", "EPCAM", "MSH2")
load("~/project/deeplearning/icb/data/tcga/scrna.v4.pcs/meta.info.RData")
input.output.genes = unique(c(extra.genes.inx, top.genes.extra, tcga.cols[c(62, 89:90, 189:510)])) #101
input.only.genes = setdiff(unique(c(topmost.cors.genes, top.cors.genes)), input.output.genes)

oxphos.sample.name = rownames(dataset_ssgsea_sel)
oxphos.dataset.new = cbind(pc.data, dataset_ssgsea_sel.norm[,input.only.genes], dataset_ssgsea_sel.norm[,input.output.genes])
output.dir="~/project/deeplearning/icb/data/oxphos/scrna.v4.genes"
dir.create(output.dir, recursive = T)
write.dataset(output.dir = output.dir, dataset = oxphos.dataset.new, samples.names = oxphos.sample.name)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.pcs/datasets_tsne_list.txt", output.dir)

# save.image("~/project/deeplearning/icb/results/sessions/process.dataset.imputation.tcga.v2.today.RData")
```
## correct the header
```{r}
xx = fread("~/project/deeplearning/icb/data/oxphos/scrna.v4.genes/val_prediction.csv")
colnames(xx) = colnames(icb.phenotype)
oxphos.deepImmuene.pred = xx
save(file="/liulab/asahu/oxphos.deepImmuene.pred.RData", oxphos.deepImmuene.pred)
```

