---
title: "TCR processing for TCGA"
output: html_notebook
---

```{r}
source("~/project/deeplearning/icb/deepImmune/data_processing/ssgsea/imputation/scRNA/epoch-142/source.proj.R")
load("~/project/deeplearning/data/tcga/tcga_extended_tcr.V3.RData")

tcga_extended_tcr[,type:=substr(reportgene, 1,3)]
# tcga_cdr3_trbv_complete = tcga_extended_tcr[ (status=='complete') & (type =="TRB") ]
tcga_extended_tcr[,aa.len:=nchar(cdr3aa)]
tcga_cdr3_trbv_complete = tcga_extended_tcr[ (status=='complete') & (type =="TRB") & (nchar(cdr3aa) <= 20)]
tcga_cdr3_trbv_complete[,cdr3aa:=as.character(cdr3aa)]
tcga_cdr3_trbv_complete[,sample.name:=substr(sample,1,12)]
tcga_cdr3_trbv_complete[,sample.name.match:=gsub(sample.name,pattern="\\-", replacement = ".")]
tcga_cdr3_trbv_complete = tcga_cdr3_trbv_complete[!grepl("\\*", cdr3aa),]
tcga.dataset = fread("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/dataset.txt")
tcga.sample.name = fread("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/samples_name.txt")
tcga.sample.name[,sample.name.match:=substr(x,1,12)]
tcga.phenotype = fread("/homes6/asahu/project/deeplearning/icb/data/tcga/scrna.v4.genes/tensorboardLog/nopipeline_vae_20190819-161104/epoch-142/tcga_val_prediction.csv")
tcga.phenotype = tcga.phenotype[unlist(tcga.phenotype$sample_name) +1]

common.samples = intersect(tcga.sample.name$sample.name.match, tcga_cdr3_trbv_complete$sample.name.match)
tcga_cdr3_trbv_match = tcga_cdr3_trbv_complete[sample.name.match %in% common.samples,]
match.inx = match(tcga_cdr3_trbv_match$sample.name.match, tcga.sample.name$sample.name.match)
tcga.phenotype.sub = tcga.phenotype[,grep("embedding", colnames(tcga.phenotype)), with = F]
tcga.phenotype.cancertype = as.factor(tcga.dataset$cancertype)
levels(tcga.phenotype.cancertype) = seq(length(levels(tcga.phenotype.cancertype)))
tcga.phenotype.cancertype = as.numeric(tcga.phenotype.cancertype)
tcga.dataset.sub = tcga.dataset[,-1,with=F]
```



## one hot encoding
```{r}
aa.one = get_one_hot_aa(cdr3aa.list = tcga_cdr3_trbv_match$cdr3aa, width=20)
dataset.tcr = cbind(cancertype=tcga.phenotype.cancertype[match.inx],   aa.one, tcga.phenotype.sub[match.inx])

# exp.match[,setdiff(exp.match.genes, if.genes)])

output.dir = "~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA"
write.dataset(output.dir = output.dir, dataset = dataset.tcr, sample.name = tcga_cdr3_trbv_match$sample.name.match)
file.copy("~/project/deeplearning/icb/deepImmune/config_files/params.json", output.dir)
file.copy("~/project/deeplearning/icb/deepImmune/config_files/datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/deepImmune/config_files/datasets_test_list.txt", output.dir)

dataset.cols = data.table(colnames(dataset.tcr), seq(ncol(dataset.tcr)))

uu = cor(aa.one.sel, dataset.tcr[,253:1119, with=F] )

xx = table(tcga_cdr3_trbv_match$sample.name.match)
tcga_cdr3.curr= tcga_cdr3_trbv_match[sample.name.match=="TCGA.3Q.A9WF"]

```



### Top 100 clonal tcrs + all input to transcriptomic deepImmune 
```{r}
max.100 <- function(score) {
    if (length(score) > 100){
        out = (min(score,na.rm = T))
    }else{
        out = sort(score,decreasing = T)[100]
    }
    out
}

# tcga_cdr3_trbv_match[, sel:=NULL]
tcga_cdr3_trbv_match[, sel:=(est_clonal_exp >= sort(est_clonal_exp, decreasing = T)[min(.N, 100)]),by=sample.name.match]
tcga_cdr3_trbv_match_sel = tcga_cdr3_trbv_match[sel==T]
match.inx = match(tcga_cdr3_trbv_match_sel$sample.name.match, tcga.sample.name$sample.name.match)
aa.one = get_one_hot_aa(cdr3aa.list = tcga_cdr3_trbv_match_sel$cdr3aa, width=20)

dataset.tcr = cbind(cancertype=tcga.phenotype.cancertype[match.inx],   tcga.dataset.sub[match.inx],  aa.one)

output.dir = "~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100"
write.dataset(output.dir = output.dir, dataset = dataset.tcr, sample.name = tcga_cdr3_trbv_match_sel$sample.name.match)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA/datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA/datasets_test_list.txt", output.dir)

```


## Non-intersecting patient in train and test set

```{r}
output.dir = "~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100.nonintersect"
write.dataset(output.dir = output.dir, dataset = dataset.tcr, sample.name = tcga_cdr3_trbv_match_sel$sample.name.match, use.sample = T, write.full.dataset = F)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100/datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100/datasets_test_list.txt", output.dir)
temp = data.table(colnames(dataset.tcr), seq_along(colnames(dataset.tcr)))
```


## Analysis of learned embedding from TCR 
1. Find TCR cluster and characterize the sequence
Associate with : 
a. Cancer type 
b. Zoom on some cancer type

```{r}
# cwd = "~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100.nonintersect/tensorboardLog/20190823-014612/epoch_10"
cwd = "~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100.nonintersect/tensorboardLog/20190826-152330/epoch_5"
dir.create(cwd)
tcr.tcga.phenotype = sprintf("%s/val_prediction.csv", cwd)
# system(sprintf("mv ~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100.nonintersect/val_prediction.csv %s", tcr.tcga.phenotype))
tcr.tcga.phenotype = fread(tcr.tcga.phenotype) 
tcr.tcga.sample.name = fread("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/TCR.AA.top100.nonintersect/samples_name.txt")
tcr.tcga.phenotype = tcr.tcga.phenotype[unlist(tcr.tcga.phenotype$sample_name) +1]
match.inx = match(tcr.tcga.sample.name$x, tcga.sample.name$sample.name.match)
tcr.tcga.phenotype$cancertype = tcga.dataset$cancertype[match.inx]
tcr.tcga.phenotype$sample.name.matched = tcr.tcga.sample.name$x
tcr.tcga.phenotype$cdr3aa = tcga_cdr3_trbv_match_sel$cdr3aa
col.pheno = colnames(tcr.tcga.phenotype)
embedding.inx = grep(colnames(tcr.tcga.phenotype), pattern = "embedding", value = T)

# pheno.inx.start = tcr.tcga.phenotype.col.dt[V1=="B_cells_naive.output"]$V2
# pheno.inx.end = tail(grep(tcr.tcga.phenotype.col.dt$V1, pattern="output$"),1)
# indexes.output = colnames(tcr.tcga.phenotype)[pheno.inx.start:pheno.inx.end]
# survival.inx.start = tcr.tcga.phenotype.col.dt[V1=="OS.time.output"]$V2
# indexes.survival = colnames(tcr.tcga.phenotype)[seq(survival.inx.start, survival.inx.start+3)]
# selected.outputs = indexes = c( embedding.inx, indexes.output, indexes.survival)


library(avinash)
library(ggplot2)
tsne.dir = sprintf("%s/tsnes",cwd)
dir.create(tsne.dir)
output.inx=grep(pattern = ".output",colnames(tcr.tcga.phenotype), value=T)
embedding.inx=grep(pattern = "embedding",colnames(tcr.tcga.phenotype), value = T)

data_tsne.merge = as.data.frame(tcr.tcga.phenotype)
# data_tsne.merge[,embedding.inx]

# all.p = plotSNE(data = data.curr , col=embedding.inx, size = 2,do.discrete=F, title= sprintf("%s %s", cell.type.curr, "response"),
#                 color.col = "response", perplexity = 30, theta = 0, pca=TRUE,
#                 filename=sprintf("%s/%s_%s_final.pdf", tsne.dir, cell.type.curr, "response"), max_iter=1000)


# dir.create(umap.param.dir, recursive = T)
n_neighbors =15; learning_rate =.01; min_dist = 0.1; pca = NULL

umap.all.p = plotUMAP(data = data_tsne.merge, col=c(embedding.inx), size=1, do.discrete=F, 
                      n_neighbors = n_neighbors, learning_rate = learning_rate, min_dist = min_dist, pca=pca,
                      title= sprintf("%s %s", cell.type.curr, "cancertype"),
                      color.col = "cancertype", 
                      filename=sprintf("%s/%s_%s_umap.pdf", tsne.dir, cell.type.curr, "cancertype"), n_epochs = 500, metric = "euclidean")


print(umap.all.p[[2]])
```

## cancer-type specific analysis
```{r}

cancer.type.curr = "SKCM"
cancertype.inx  = which(data_tsne.merge$cancertype==cancer.type.curr)
data.curr = data_tsne.merge[cancertype.inx,]
# n_neighbors =15; learning_rate =.01; min_dist = 0.1; pca = NULL

fac = "T_cells_CD8"
library(uwot)
umap.model <- umap(as.matrix(data.curr[, c(embedding.inx)]), 
                   n_threads = 32, ret_model = T, n_neighbors = 100, pca=5)


# umap.curr = plotUMAP(data = data.curr, col=c(embedding.inx), size=1, do.discrete=F, 
#                                 n_neighbors = n_neighbors, learning_rate = learning_rate, min_dist = min_dist, pca=pca,
#                       title= sprintf("%s %s", cell.type.curr, fac),
#                       color.col = "T_cells_CD8", 
#                       filename=sprintf("%s/%s_%s_umap.pdf", tsne.dir, cell.type.curr, "T_cells_CD8"), n_epochs = 500, metric = "euclidean")
```

```{r}
save.dir = sprintf("%s/%s/umap/", tsne.dir, cancer.type.curr)
dir.create(save.dir,recursive = T)
data.clust = as.data.frame(umap.model$embedding)
xx = color.clusters.features( data=data.curr[data.clust$V1 > 0,], cluster=data.clust[data.clust$V1 > 0,],  color.cols = fac,
                              title="UMAP",size=1, filename=sprintf("%s/if_", save.dir), normalize=F, do.discrete=F)

# summary(data.curr[data.clust$V1 > 0,]$DSS.filtered)
# summary(data.curr[data.clust$V1 < 0,]$DSS.filtered)

xx = color.clusters.features( data=data.curr, cluster=data.clust,  color.cols = colnames(data.curr)[2:473],
                              title="UMAP",size=1, filename=sprintf("%s/if_", save.dir), normalize=F, do.discrete=F)
```

```{r}
library(survival)
# testing coxph 
# tt = rnorm(100)
# test1 <- list(time=tt, 
#               status=rep(1,100), 
#               x=tt) 
#               
# aa = coxph(Surv(time, status) ~ x  test1) 
data.curr.unqiue = data.curr[!duplicated(data.curr$sample.name.matched),]
aa = coxph(Surv(OS.time, OS.filtered) ~  OS.time.output, data.curr.unqiue)
```

## Visualize the sequence 
```{r}
# viusalize.cdr3.repel <- function(data, cluster,  color.cols = "condition",
#                                     title="t-SNE",size=0.25,do.discrete=T, filename=NULL, normalize=TRUE, shape = 1){
require(viridis)
require(ggthemes)
require(ggrepel)
dt1 = data.table(data.curr)
dt1 = cbind(dt1, data.clust)
# title.curr = sprintf("%s_%s", title, color.col)
dt2 = dt1[abs(V1)<5 & abs(V2)< 5 ]
dt2 = dt1[V1< -10 & V2> 15 ]
p=ggplot(dt2, aes(x=V1, y=V2)) +
    geom_point(size=1,aes(color=T_cells_CD8, ), alpha=0.7) +
    xlab("Dim1") + ylab("Dim2") +
    # ggtitle(label = title.curr) +
    theme_light(base_size=5) +
    # theme(axis.text.x=element_blank(),
    #       axis.text.y=element_blank()) + 
    geom_text_repel(
        # data = dt2[sample(nrow(dt2), size=100)],
        data = dt2,
        aes(x=V1, y=V2, label = cdr3aa),
        size = 2,
        box.padding = unit(0.35, "lines"),
        point.padding = unit(0.3, "lines")
    ) +
    theme(legend.position = "none")

if (do.discrete) {
    
    colorCount = length(unique(d_cluster_1$col))
    if(colorCount > 8){
        getPalette = colorRampPalette(brewer.pal(9, "Set1"))
        p =  p + scale_fill_manual(values = getPalette(colorCount))
    }else{
        p<- p+ scale_colour_brewer(palette = "Set2")
    }
    
}else{
    # p <- p+  scale_color_viridis() 
    p <- p+ scale_color_gradientn(colours = heat.colors(20, alpha=0.7, rev=T))
    
    # p <- p +   
    #     scale_colour_gradient_tableau(palette="Classic Red") +
    #     theme_classic() + theme(legend.position = "none") 
    # 
}


```

