---
title: "Analysis of Tgd in TCGA"
output: html_notebook
---


```{r}
library(survminer)
library(survival)
library(magrittr)
library(tidyr)
library(data.table)
```


```{r}
library(SingleR)

myFastCor.multicores = function(x,y, method="spearman", num=20000, nthreads=1){
    if(is.null(num))  num=0
    if(nthreads>1){
      split.size = floor(ncol(y)/nthreads)
        splits = lapply(seq(nthreads), function(tt){
          start = (tt-1)* split.size +1
          end = ifelse(tt< nthreads, tt*split.size, ncol(y))
          seq(start, end)
        })
        out = mclapply(splits, function(tt) myFastCor(x=x,y=y[,tt], method=method, num=num), mc.cores = nthreads) %>%
            do.call(cbind,.) %>% set_colnames(colnames(y))
    }else{
        out = myFastCor(x=x,y=y, method=method, num=num)
    }
    out
}


myFastCor <- function(x,y, method="spearman", num=20000) {
    if (ncol(x) < num | ncol(y) < num){
        out = cor(x, y, method="spearman", use="pairwise.complete.obs")
    }else{
        if(method=="spearman"){
            x%<>%
                apply(.,2, rank, na.last="keep")
            y%<>%
                apply(.,2, rank, na.last="keep")
        }
        out = WGCNA::cor(x, y, use="pairwise.complete.obs")
    }
    out
}
calcCorEnrich <- function(x,y, num=NULL, nthreads=1) {
  rownames(x) %<>% toupper
  rownames(y) %<>% toupper
    common = intersect(rownames(x), rownames(y))
    myFastCor.multicores(x[common,], y[common,], num=num, nthreads = nthreads)
}


data.name="HumanPrimaryCellAtlasData"
ref.se =  eval(parse(text=paste0(data.name, "()"))) 
col.dat = colData(ref.se)
col.dat$Var1= paste(rownames(col.dat),seq(nrow(col.dat)))  
col.dat = as.data.table(col.dat)
ref.exp = assay(ref.se) %>%
  t() %>% scale(., center=T, scale=T) %>% t()
rownames(ref.exp) %<>% toupper
colnames(ref.exp) = col.dat$Var1

```

```{r}
tcga.surv.genes = readRDS("~/liulab_home/data/tcga/tcga.cox.genes.Rds")
tcga.dataset = fread("~/project/deeplearning/icb/data/tcga/scrna.v4.allgenes.nopcs/dataset.txt")
tcga.sample = fread("~/project/deeplearning/icb/data/tcga/scrna.v4.allgenes.nopcs/samples_name.txt")

if.start.inx = which(colnames(tcga.dataset)== "B_cells_naive")
dataset.col = colnames(tcga.dataset)
# if.factors = tcga.dataset[,seq(if.start.inx, ncol(tcga.dataset)),with=F]
surv.factors = tcga.dataset[,length(dataset.col) + seq(8)-8, with =F]
exp.tcga = tcga.dataset[,seq(2,if.start.inx-1), with=F] %>% as.matrix %>%
  scale(.,scale=T, center=T)
genes.sel= tcga.surv.genes$OS[order(P)[1:500]]$genes
mat.signature.enrich = exp.tcga[,genes.sel] %>% t() %>%
  calcCorEnrich( ., ref.exp, num=NULL, nthreads =40)

gamma.delta.score = which(ref.se@colData$label.fine=="T_cell:gamma-delta") %>% 
  mat.signature.enrich[,.] %>% rowMeans(., na.rm=T)

patient.sel = lapply(c(-0.46, -.2, 0, .3, .67), function(tt)
  which.min(abs(gamma.delta.score - tt))) %>% unlist

common.genes = intersect(rownames(gdT.exp), genes.sel)
gdT.exp = ref.exp[,which(ref.se@colData$label.fine=="T_cell:gamma-delta")]
avi.dt = data.table(ref=gdT.exp[common.genes, 1], bulk=c(unlist(t(exp.tcga[patient.sel,common.genes]))), label = rep(paste("TCGA", 1:5), each=length(common.genes)))
p = ggscatter(avi.dt, x = "ref", y = "bulk",
          add = "reg.line",                                 # Add regression line
          conf.int = FALSE,                                  # Add confidence interval
          color = "label"
          )+
  stat_cor(aes(color=as.factor(label)), method = "spearman", label.x = 3) +
  ylab("Normalized expression in TCGA") +  
  xlab("Normalized expression in Gamma delta")

ggsave(".figs/TCGA_gtd_correlation.pdf", p)


surv.factors$Tgd = gamma.delta.score
surv.factors$cancertype = tcga.dataset$cancertype
quantize = function(tt, prob.max=0.5, prob.min=0.5) {
  thr.max = quantile(tt,probs=prob.max)
  thr.min = quantile(tt,probs=prob.min)
  ifelse(tt > thr.max, 1, ifelse(tt<thr.min, 0, NA))
}
surv.factors[,Tgd.q:=quantize(Tgd, 0.75, 0.4), by=cancertype]
# aa = subset(colon,rx=="Lev+5FU")
cancer.sel = table(surv.factors$cancertype) %>% sort(.,decreasing=T) %>% 
       names %>% head(.,20)
sur.factors.curr = surv.factors[(cancertype %in% cancer.sel) & (!is.na(Tgd.q))]
# sur.factors.curr = surv.factors
fit1 <- survfit( Surv(OS.time, OS.filtered) ~ Tgd.q, data = sur.factors.curr )
p1 = ggsurvplot(fit1, sur.factors.curr, 
                palette = "jco", pval = TRUE)
ggsave(filename=".figs/tcga_gtd_combined.pdf", print(p1))

p = ggsurvplot_facet( fit1, sur.factors.curr[cancertype %in% cancer.sel[1:16]], facet.by = "cancertype", 
                palette = "jco", pval = TRUE)

ggsave(filename=".figs/tcga_gtd_16cancer.pdf", p, width = 12, height = 8)


p = ggsurvplot_facet( fit1, sur.factors.curr[cancertype %in% "SKCM"], facet.by = "cancertype", 
                palette = "jco", pval = TRUE)

ggsave(filename=".figs/tcga_gtd_skcm.pdf", p)
surv.factors[,Tgd.q:=quantize(Tgd, 0.75, 0.4), by=cancertype]
# aa = subset(colon,rx=="Lev+5FU")

quantize_gradient = function(tt, grades=4) {
  thrs = seq(0,1,length.out = grades+1)
 thrs = quantile(tt,probs=thrs[-c(1,length(thrs))])
  sapply(tt, function(uu) sum(thrs<uu))
}
surv.factors[,Tgd.q:=quantize_gradient(Tgd, 4), by=cancertype]

cancer.sel = table(surv.factors$cancertype) %>% sort(.,decreasing=T) %>% 
       names %>% head(.,20)
sur.factors.curr = surv.factors[(cancertype %in% cancer.sel) & (!is.na(Tgd.q))]
# sur.factors.curr = surv.factors
fit1 <- survfit( Surv(OS.time, OS.filtered) ~ Tgd.q, data = sur.factors.curr )
p1 = ggsurvplot(fit1, sur.factors.curr, 
                palette = "jco", pval = TRUE)
ggsave(filename=".figs/tcga_gtd_combined_grades.pdf", print(p1))

p = ggsurvplot_facet( fit1, sur.factors.curr[cancertype %in% cancer.sel[1:16]], facet.by = "cancertype", 
                palette = "jco", pval = TRUE)

ggsave(filename=".figs/tcga_gtd_16cancer_grades.pdf", p, width = 12, height = 8)


p = ggsurvplot_facet( fit1, sur.factors.curr[cancertype %in% "SKCM"], facet.by = "cancertype", 
                palette = "jco", pval = TRUE)
ggsave(filename=".figs/tcga_gtd_skcm_grades.pdf", p)


```
## survival analysis in ICB cohort 

```{r}

icb.exp = fread("~/liulab_home/data/ssgsea/xiaoman/icb/expression/Mariathasan2018_PDL1_Bladder_RNASeq_mUC")
icb.followup =  fread("~/liulab_home/data/ssgsea/xiaoman/icb/follow_up/Mariathasan2018_PDL1_Bladder_RNASeq_mUC") 
icb.exp.mat = icb.exp[,-1] %>% as.matrix %>%
    set_rownames(toupper(icb.exp$Symbol)) %>% t() %>%
  set_colnames(toupper(rownames(icb.exp.mat))) %>% 
     scale(., center=T, scale=T) %>% t()
icb.followup = icb.followup[ match(Patient,colnames(icb.exp.mat))]
genes.curr = intersect(rownames(icb.exp.mat), toupper(genes.sel))

mat.signature.enrich = icb.exp.mat[genes.curr, ]  %>%
  calcCorEnrich( ., ref.exp, num=NULL, nthreads =40)

gamma.delta.score = which(ref.se@colData$label.fine=="T_cell:gamma-delta") %>% 
  mat.signature.enrich[,.] %>% rowMeans(., na.rm=T)

icb.followup$Tgd = gamma.delta.score

icb.followup[,Tgd.q:=quantize(Tgd, 0.75, 0.4)]
# aa = subset(colon,rx=="Lev+5FU")
sur.factors.curr = icb.followup[ (!is.na(Tgd.q))]
# sur.factors.curr = icb.followup
fit1 <- survfit( Surv(OS, OS.Event) ~ Tgd.q, data = sur.factors.curr )
p1 = ggsurvplot(fit1, sur.factors.curr, 
                palette = "jco", pval = TRUE)
pdf(".figs/icb/genentech_gtd.pdf")
print(p1)
dev.off()


icb.followup[,Tgd.q:=quantize_gradient(Tgd, 4)]

sur.factors.curr = icb.followup[(!is.na(Tgd.q))]
# sur.factors.curr = icb.followup
fit1 <- survfit(Surv(OS, OS.Event)~ Tgd.q, data = sur.factors.curr )
p1 = ggsurvplot(fit1, sur.factors.curr, 
                palette = "jco", pval = TRUE)
pdf(".figs/icb/genentech_gtd_grades.pdf")
print(p1)
dev.off()


px = pROC::roc(icb.followup$Response, icb.followup$Tgd)
pdf(".figs/icb/genentech_gtd_response.pdf")
plot(px)
dev.off()

```
```{r}

bulk.deg.dt = readRDS("/homes6/asahu/liulab_home/data/immunotherapy-trials/all.bulk.rnaseq.deg.Rds")
var.genes = readRDS("~/liulab_home/data/single_cell/Lee_data/lee.seurat.cd3.vargenes.RDS")
bulk.deg.temp = dcast(gene~type, data=bulk.deg.dt, value.var = "deg.effect", fill = NA) 
bulk.deg.mat = bulk.deg.temp[,-1,with=F] %>%
    as.matrix() %>%
    set_rownames(bulk.deg.temp$gene)


gdT.exp = ref.exp[,which(ref.se@colData$label.fine=="T_cell:gamma-delta")]
aa = calcCorEnrich(gdT.exp, bulk.deg.mat)
library(ggpubr)
common.genes = intersect(rownames(gdT.exp), rownames(bulk.deg.mat))
bb = cor(gdT.exp[common.genes,], bulk.deg.mat[common.genes,], method = "spearman")

avi.dt = data.table(ref=c(unlist(gdT.exp[common.genes, ])), bulk=bulk.deg.mat[common.genes, "combined"], label = rep(c("rep1", "rep2"), each=length(common.genes)))
p = ggscatter(avi.dt, x = "ref", y = "bulk",
          add = "reg.line",                                 # Add regression line
          conf.int = FALSE,                                  # Add confidence interval
          color = "label"
          # add.params = list(color = "blue",
          #                   fill = "lightgray")
          )+
  stat_cor(aes(color=as.factor(label)), method = "spearman", label.x = 3) +
  ylab(" Responder vs. non-resp bulk ICB (-log Pvalue)") +  
  xlab("Normalized expression in Gamma delta")

ggsave(".figs/icb/icb_gtd_correlation.pdf", p)

```
```{r}
tcga.surv.genes = readRDS("~/liulab_home/data/tcga/tcga.cox.genes.Rds")

p = EnhancedVolcano::EnhancedVolcano(tcga.surv.genes$OS,
	lab = tcga.surv.genes$OS$genes,
	x = 'z',
	y = 'P',
	pCutoff = 1E-10,
	FCcutoff = 1,
	# pointSize = c(ifelse(lm22.enrich$padj< 5E-2, 4, 3)),
	labSize = 4.0,
	legend=c('NS','Log (base 2) fold-change','Adj.P value',
		'Adj.P value & Log (base 2) fold-change'),
	legendPosition = 'right',
	legendLabSize = 8,
	legendIconSize = 4.0,
	drawConnectors = TRUE,
	widthConnectors = 0.2,
	colAlpha = 0.8,
	colConnectors = 'grey30'
	)
ggsave(file=".figs/tcga.surv.OS.genes.pdf", p)

```
## TRUST4 
```{r}
tcga.sample[,name:=gsub("\\.", x, replacement = "-")] 
tcga.skcm = tcga.sample[tcga.dataset$cancertype=="SKCM"]
surv.factors$name = tcga.sample$name
surv.factors.skcm = surv.factors[tcga.dataset$cancertype=="SKCM"]
seqdetpth = fread("/liulab/lsong/projects/TRUST4_TCGA/tcga_seqDepth.txt")
trust4 = fread("/liulab/lsong/projects/TRUST4_TCGA/tcga_simpleRepNoPartial.out")
process.label = function(tt){
  substring(tt,1,16) %>% gsub("-", ., replacement = ".")
}
trust4[,name:=substring(V1, 1, 16)]
trust4.skcm =trust4[name %in% tcga.skcm$name]
trust4.skcm.trg = trust4.skcm[grepl("^TRG", V6)|grepl("^TRG", V7)| grepl("^TRG", V8)|grepl("^TRG", V9)] %>% 
  .[!(V5 %in% c("out_of_frame", "_"))]
trust4.skcm.trg.summ = trust4.skcm.trg[,.(total.trgs=sum(V2), V1=unique(V1)), by=name]
trust4.skcm.trg.summ$seqdtpth = seqdetpth[match(trust4.skcm.trg.summ$V1, V1)]$V2
trust4.skcm.trg.summ[,norm.trg:=total.trgs*1E7/seqdtpth]
surv.factors.skcm$norm.trg = trust4.skcm.trg.summ$norm.trg[match(surv.factors.skcm$name, trust4.skcm.trg.summ$name)]
surv.factors.skcm[,norm.trg:=ifelse(is.na(norm.trg),0, norm.trg)]
surv.factors.skcm[,Tgd.r:=rank(Tgd)]
p = ggscatter(surv.factors.skcm, y= "Tgd.r", x = "norm.trg",
          conf.int = FALSE,                                  # Add confidence interval
          add.params = list(color = "blue",
                            fill = "lightgray")
          )+
  stat_cor(method = "spearman", label.x=3) +
  ylab("gdT human atlas ") +  
  xlab("gdT TRUST") 
ggsave(".figs/gtd_trust4_correlation.pdf", p)


```

