---
title: "Validation of David Liu data"
output: html_notebook
---
## get list of TF

```{r}
# BiocManager::install("CoRegNet")
library(CoRegNet)
data(HumanTF)
crs = fread("~/liulab_home/data/ssgsea/xiaoman/annotation/EpiGenes_main.csv")$HGNC_symbol
trs = unique(c(HumanTF, crs))
# length(trs)
```


```{r echo=False}
output.dir = "~/project/deeplearning/icb/data/tcga/tf"
bb  = fread("/liulab/asahu/data/ssgsea/xiaoman/TCGA_ALLTPM.txt")
tcga.dataset = fread("~/project/deeplearning/icb/data/tcga/citokines.v1/dataset.txt")
samplename.dataset = fread("~/project/deeplearning/icb/data/tcga/citokines.v1/samples_name.txt")$x
dataset.phenotype = tcga.dataset[,1346: 1540, with=F]
sample.metadata = data.table(sample.id=colnames(bb)[-1])
sample.metadata[,patient.id:=substring(sample.id, 1, 12)]
sample.metadata[,is.normal:=substring(sample.id, 14, 14)]

sample.metadata$is.present = sample.metadata$sample.id %in% samplename.dataset 
sample.metadata[,sel:=(is.present & is.normal==0)]
sample.metadata$cancertype = tcga.dataset[match(sample.metadata$sample.id, samplename.dataset)]$cancertype
expression_mat= t(as.matrix(bb[,seq(2,ncol(bb)),with=F]))
expression_mat = expression_mat[sample.metadata$sel, ]
phenotype.matched = dataset.phenotype[match(rownames(expression_mat), samplename.dataset),]
colnames(expression_mat) = bb$gene_name
pcgs = fread("/liulab/asahu/data/ssgsea/xiaoman/./pcg.txt")
load("/liulab/asahu/data/ssgsea/xiaoman/commmon.genes.RData")
common.genes = intersect(colnames(expression_mat), intersect(common.genes, trs))
expression_mat1 = expression_mat[ ,common.genes] 
expresion_mat1 = avinash::impute.closest.gene(common.genes = common.genes, expression_mat)
stopifnot(any(!is.na(expression_mat)))
patient.name = rownames(expression_mat1)
patient.name = gsub(patient.name, pattern="-", replacement=".")
rownames(expression_mat1) = patient.name

dataset_ssgsea_sel = avinash::normalize.expression(expression_mat1, num.samp.thr =0) 
ref.expression = dataset_ssgsea_sel
ref.cancertype = sample.metadata[sel==T,]$cancertype
save(file=paste0(output.dir, "/ref.expression.RData"), ref.expression)
save(file=paste0(output.dir, "/ref.cancertype.RData"), ref.cancertype)
genes.analyzed = common.genes
save(file=paste0(output.dir, "/genes.analyzed.RData"), genes.analyzed)

dataset.new = cbind(cancertype=ref.cancertype, dataset_ssgsea_sel, phenotype.matched)

avinash::write.dataset(output.dir = output.dir, dataset = dataset.new, sample.name = rownames(dataset_ssgsea_sel))
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/simple/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/simple//datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/scrna.v4.genes/simple/datasets_test_list.txt", output.dir)

# barcode = substring(rownames(dataset_ssgsea_sel), 1,12)
```

## genentech data 
```{r}
output.dir = "~/project/deeplearning/icb/data/genentech.tpm/tf/"
dataset_ssgsea = "/liulab/asahu/data/ssgsea/xiaoman/Genetech_expression_TPM.txt"

pathway_order = "/liulab/asahu/data/ssgsea/xiaoman/ssgsea.order_tcga.txt"
dataset_phenotype = "/liulab/asahu/data/ssgsea/xiaoman/Avin/clinical_ICB_oxphos.txt"

ref.expression.RData = "~/project/deeplearning/icb/data/tcga/tf/ref.expression.RData"
ref.cancertype.RData = "~/project/deeplearning/icb/data/tcga/tf/ref.cancertype.RData"
load("~/project/deeplearning/icb/data/tcga/tf/genes.analyzed.RData"); common.genes = genes.analyzed
load(ref.expression.RData)
load(ref.cancertype.RData)

dir.create(output.dir, showWarnings = FALSE)

dataset_ssgsea = fread(dataset_ssgsea)
dataset_phenotype = fread(dataset_phenotype)
genentech.env = local({load("/liulab/asahu/data/ssgsea/xiaoman/genentech.phenotype.RData");environment()})
dataset_ssgsea_mat= t(as.matrix(dataset_ssgsea[,seq(2,ncol(dataset_ssgsea)),with=F]))
setnames(dataset_ssgsea, 1, "gene_name")
colnames(dataset_ssgsea_mat) = dataset_ssgsea$gene_name
dataset_ssgsea_mat = dataset_ssgsea_mat[ ,common.genes] 

patient.name = rownames(dataset_ssgsea_mat)
patient.name = gsub(patient.name, pattern="-", replacement=".")
rownames(dataset_ssgsea_mat) = patient.name

# phenotype data
setnames(dataset_phenotype, 1, "patient.name")
dataset_phenotype$patient.name = gsub(dataset_phenotype$patient.name, pattern="-", replacement=".")
only_in_phenotype = setdiff(dataset_phenotype$patient.name, patient.name)
only_in_ssgsea = setdiff( patient.name, dataset_phenotype$patient.name)
common.patients = intersect(patient.name, dataset_phenotype$patient.name)
dataset_ssgsea_sel = dataset_ssgsea_mat[match(common.patients, patient.name), ] 

phenotype_sel = dataset_phenotype[match(common.patients, dataset_phenotype$patient.name)]
colnames(phenotype_sel) = gsub(colnames(phenotype_sel), pattern=" ", replacement="_")
colnames(phenotype_sel) = gsub(colnames(phenotype_sel), pattern="-", replacement="_")

dataset_ssgsea_norm = normalize.expression(dataset_ssgsea_sel)

ref.expression.cancertype = ref.expression[ref.cancertype=="BLCA",] 
dataset_ssgsea_matched = match.expression.distribution(dataset_ssgsea_sel, ref.expression.cancertype)

phenotype_sel.mod = phenotype_sel
phenotype_sel.mod[, Response:=as.double(Response)]


# neoantigen.pheno

reorder = match(rownames(dataset_ssgsea_sel), rownames(genentech.env$genentech.pheno))
genentech.pheno = genentech.env$genentech.pheno[reorder,]
neoantigen.pheno = data.table(Silent.Mutation.Rate=genentech.pheno$FMOne.mutation.burden.per.MB, SNV.Neoantigens =genentech.pheno$Neoantigen.burden.per.MB)
cibersort = phenotype_sel.mod[,5:37,with=F]
other.phenotype.temp = genentech.pheno[,c(1,3:5,23:25)] 
other.phenotype.one = mltools::one_hot(data.table(other.phenotype.temp), sparsifyNAs =T)
other.phenotype.one$Lund = NULL
other.phenotype.one$Best_NE = NULL
other.phenotype = other.phenotype.one[, which(colSums(other.phenotype.one) > 20),with=F][,-(1:4),with=F]
response.dt = cbind(  other.phenotype.one[,1:4, with=F], phenotype_sel.mod[,c(4,2:3),with=F])
dataset.genentech = cbind(cancertype="BLCA", dataset_ssgsea_matched, cibersort, other.phenotype, neoantigen.pheno, response.dt)
dataset.genentech.nan = dataset.genentech[!is.na(Response)]
aa = data.table(colnames(dataset.genentech), seq(ncol(dataset.genentech)))
print(aa)
                
output.dir = "~/project/deeplearning/icb/data/genentech.tpm//tf/"
avinash::write.dataset(output.dir = output.dir, dataset = dataset.genentech.nan, sample.name = phenotype_sel.mod[!is.na(Response)]$patient.name)
file.copy("~/project/deeplearning/icb/data/tcga/tf/tensorboardLog/bottleneck20200206-101221/params.json", output.dir,overwrite = T)
file.copy("~/project/deeplearning/icb/data/tcga/tf/datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/tf/datasets_test_list.txt", output.dir)
```

## Binarize the data 

```{r}
binarize.expression = function(x, prob=0.75){
	x1 = x[x>0]
	thr = quantile(x1, probs=prob)
	x1 = ifelse(x1 > thr, 1, 0)
	x[x>0] = x1
	x
}
```


## binary tcga
```{r}

tcga.exp  = fread("/liulab/asahu/data/ssgsea/xiaoman/TCGA_ALLTPM.txt")
tcga.sample.sel = fread("~/project/deeplearning/icb/data/tcga/tf/samples_name.txt")
tcga.phenotypes = fread("~/project/deeplearning/icb/data/tcga/tf/dataset.txt")
sample.inx = match(tcga.sample.sel$x, colnames(tcga.exp))
genes.inx = match(genes.analyzed, tcga.exp$gene_name)
phenotype.inx = seq(2123,2317)
continuous.exp = t(as.matrix(tcga.exp[genes.inx,sample.inx,with=F]))
colnames(continuous.exp) = genes.analyzed
tcga.phenotypes.sel = tcga.phenotypes[,phenotype.inx,with=F]
bin.exp  = apply(continuous.exp,2, binarize.expression)
tcga.dataset = cbind(cancertype=tcga.phenotypes$cancertype, continuous.exp, bin.exp, tcga.phenotypes[,phenotype.inx,with=F])
output.dir = "~/project/deeplearning/icb/data/tcga/tf/binarize"
write.dataset(output.dir = output.dir, dataset =tcga.dataset , sample.name = tcga.sample.sel$x)
file.copy("~/project/deeplearning/icb/data/tcga/tf/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/tf//datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/tcga/tf//datasets_test_list.txt", output.dir)
```

## binary genentech 
```{r}
genentech.exp  = fread("/liulab/asahu/data/ssgsea/xiaoman/Genetech_expression_TPM.txt")
genentech.sample.sel = fread("~/project/deeplearning/icb/data/genentech.tpm/tf/samples_name.txt")
genentech.phenotypes = fread("~/project/deeplearning/icb/data/genentech.tpm/tf/dataset.txt")
sample.inx = match(genentech.sample.sel$x, colnames(genentech.exp))
genes.inx = match(genes.analyzed, genentech.exp$V1)
continuous.exp = t(as.matrix(genentech.exp[genes.inx,sample.inx,with=F]))
colnames(continuous.exp) = genes.analyzed

bin.exp  = apply(continuous.exp,2, binarize.expression)
genentech.phenotypes.sel = data.table(matrix(NA,ncol=ncol(tcga.phenotypes.sel) ,nrow =nrow(continuous.exp)))
colnames(genentech.phenotypes.sel) = colnames(tcga.phenotypes.sel)
genentech.pheno.matched = genentech.pheno[genentech.sample.sel$x,]
genentech.phenotypes.sel$Nonsilent.Mutation.Rate = genentech.pheno.matched$FMOne.mutation.burden.per.MB
genentech.phenotypes.sel$SNV.Neoantigens = genentech.pheno.matched$Neoantigen.burden.per.MB
genentech.phenotypes.sel$OS.time = genentech.pheno.matched$OS
genentech.phenotypes.sel$OS.filtered = genentech.pheno.matched$Event

genentech.dataset = cbind(cancertype=genentech.phenotypes$cancertype, continuous.exp, bin.exp, genentech.phenotypes.sel)
output.dir = "~/project/deeplearning/icb/data/genentech.tpm/tf/binarize"
write.dataset(output.dir = output.dir, dataset = genentech.dataset, sample.name = genentech.sample.sel$x)
file.copy("~/project/deeplearning/icb/data/genentech/tf/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/genentech/tf//datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/genentech/tf//datasets_test_list.txt", output.dir)

```

## Response prediction
```{r}
surv.predicted = fread("~/project/deeplearning/icb/data/tcga/tf//binarize/tensorboardLog/surv_noaug_20200218-011346/genentech_70.csv")
Neo.predicted = fread("~/project/deeplearning/icb/data/tcga/tf/binarize/tensorboardLog/Neo_20200217-233533/genentech_100.csv")
library(pROC)

auc(predictor = surv.predicted$embedding2, response = genentech.pheno.matched$Response)
aa = roc(predictor = surv.predicted$OS.time.output, response = genentech.pheno.matched$Response)
auc(predictor = Neo.predicted$SNV.Neoantigens.output, response = genentech.pheno.matched$Response)
auc(predictor = Neo.predicted$SNV.Neoantigens, response = genentech.pheno.matched$Response)
auc(predictor = Neo.predicted$embedding3, response = genentech.pheno.matched$Response)

bb = roc(predictor = Neo.predicted$SNV.Neoantigens.output, response = genentech.pheno.matched$Response)
plot(bb)
```


## TCGA not working 
## there are missing data and imputation is not perfect

```{r eval=FALSE}

output.dir = "~/project/deeplearning/icb/data/tcga/tf"
bb  = fread("/liulab/asahu/data/ssgsea/xiaoman/TCGA_gdc/EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv")
dataset_ssgsea = "/liulab/asahu/data/ssgsea/xiaoman/TCGA_ALLTPM.txt"
sample.metadata = data.table(sample.id=colnames(bb)[-1])
sample.metadata[,patient.id:=substring(sample.id, 1, 12)]
sample.metadata[,is.normal:=substring(sample.id, 14, 14)]

cc  = readxl::read_excel("/liulab/asahu/data/ssgsea/xiaoman/TCGA_gdc/TCGA-CDR-SupplementalTableS1.xlsx", sheet = 1)
sample.metadata$is.present = sample.metadata$patient.id %in% cc$bcr_patient_barcode
sample.metadata[,sel:=(is.present & is.normal==0)]
expression_mat= t(as.matrix(bb[,seq(2,ncol(bb)),with=F]))
expression_mat = expression_mat[sample.metadata$sel, ]
col.name = sapply(bb$gene_id, function(tt) strsplit(tt,split="\\|")[[1]][1])
withname = which(col.name!="?")
expression_mat =expression_mat[,withname]
colnames(expression_mat) = col.name[withname]
pcgs = fread("/liulab/asahu/data/ssgsea/xiaoman/./pcg.txt")
load("/liulab/asahu/data/ssgsea/xiaoman/commmon.genes.RData")
common.genes = intersect(col.name, trs)
expression_mat1 = expression_mat[ ,common.genes] 
expresion_mat1 = avinash::impute.closest.gene(common.genes = common.genes, expression_mat)
stopifnot(any(!is.na(expression_mat)))
patient.name = rownames(expression_mat)
patient.name = gsub(patient.name, pattern="-", replacement=".")
rownames(expression_mat) = patient.name

dataset_ssgsea_sel = avinash::normalize.expression(expression_mat, num.samp.thr =0) 
ref.expression = dataset_ssgsea_sel
ref.cancertype = sample.metadata[sel,]$type
save(file=paste0(output.dir, "/ref.expression.RData"), ref.expression)
save(file=paste0(output.dir, "/ref.cancertype.RData"), ref.cancertype)
pca=F
if(pca){
    # load(pca_obj.RData)
    temp_out = avinash::get_pca(dataset_ssgsea_sel, pca_obj = NULL, scale=F, subsample=.4) 
        # temp_out = get_pca(dataset_ssgsea_sel, subsample=.2) 
    pca_obj = temp_out$pca_obj
    pca_obj$len_selected = 50
    save(file=paste0(output.dir, "/pca_obj.RData"), pca_obj)
    pca_out_sel = temp_out$pca_out[,seq(pca_obj$len_selected)]
    general.pcs = pca_out_sel
    # dataset_ssgsea_sel = pca_out_sel 
}
write.dataset(output.dir = output.dir, dataset = dataset.new, sample.name = rownames(expression_match_norm))
file.copy("~/project/deeplearning/icb/data/Getz_scRNA/TCR.AA.V2/params.json", output.dir)
file.copy("~/project/deeplearning/icb/data/Getz_scRNA/TCR.AA.V2/datasets_tsne_list.txt", output.dir)
file.copy("~/project/deeplearning/icb/data/Getz_scRNA/TCR.AA.V2/datasets_test_list.txt", output.dir)
 
# barcode = substring(rownames(dataset_ssgsea_sel), 1,12)
```

## correct phenotype file in Mariathasan 
```{r}
gene.pheno = data.table(genentech.env$aa)
gene.pheno.dt = gene.pheno[, .(OS=gene.pheno$os, OS.Event=censOS, Response = ifelse(binaryResponse %in% "CR/PR", 1,  ifelse(binaryResponse %in% "SD/PD", 0, NA))
                                                                                 , Neoantigen=`Neoantigen burden per MB`)]
gene.pheo1 = cbind(Patient=rownames(genentech.env$aa), gene.pheno.dt)

write.table(file="~/liulab_home/data/ssgsea/xiaoman/icb/followup_my/my_Mariathasan2018_PDL1_Bladder_RNASeq_mUC",x=gene.pheo1, sep="\t", quote=F, col.names = T, row.names = T)
```

