---
title: "SCN annotation"
output: html_notebook
---


```{r}
stPark = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/sampTab_Park_MouseKidney_062118.rda")
expPark = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/expMatrix_Park_MouseKidney  ")
dim(expPark)
genesPark = rownames(expPark)
rm(expPark)
gc()
expTMraw = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/expMatrix_TM_Raw_Oct_12_2018.rda")
stTM = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/sampTab_TM_053018.rda")
stTM<-droplevels(stTM)
commonGenes = intersect(rownames(expTMraw), genesPark)

```

```{r}
set.seed(100) #can be any random seed number
stList = splitCommon(sampTab=stTM, ncells=100, dLevel="newAnn")
stTrain = stList[[1]]
expTrain = expTMraw[,rownames(stTrain)]
```

```{r}
system.time(class_info<-scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 10, nRand = 70, nTrees = 1000, nTopGenePairs = 25, dLevel = "newAnn", colName_samp = "cell"))
```

```{r}
#validate data
stTestList = splitCommon(sampTab=stList[[2]], ncells=100, dLevel="newAnn") #normalize validation data so that the assessment is as fair as possible
stTest = stTestList[[1]]
expTest = expTMraw[commonGenes,rownames(stTest)]

#predict
classRes_val_all = scn_predict(cnProc=class_info[['cnProc']], expDat=expTest, nrand = 50)
```

```{r}
#Create a name vector label used later in classification heatmap where the values are cell types/ clusters and names are the sample names
 
nrand = 50
sla = as.vector(stTest$newAnn)
names(sla) = as.vector(stTest$cell)
slaRand = rep("rand", nrand) 
names(slaRand) = paste("rand_", 1:nrand, sep='')
sla = append(sla, slaRand) #include in the random cells profile created

sc_hmClass(classMat = classRes_val_all,grps = sla, max=300, isBig=TRUE)
```

```{r}
gpTab = compareGenePairs(query_exp = expTest, training_exp = expTrain, training_st = stTrain, classCol = "newAnn", sampleCol = "cell", RF_classifier = class_info$cnProc$classifier, numPairs = 20, trainingOnly= TRUE)

train = findAvgLabel(gpTab = gpTab, stTrain = stTrain, dLevel = "newAnn")

hm_gpa_sel(gpTab, genes = class_info$cnProc$xpairs, grps = train, maxPerGrp = 50)
```

```{r}
expPark = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/expMatrix_Park_MouseKidney_Oct_12_2018.rda") 
  
nqRand = 50
system.time(crParkall<-scn_predict(class_info[['cnProc']], expPark, nrand=nqRand))

sgrp = as.vector(stPark$description1)
names(sgrp) = as.vector(stPark$sample_name)
grpRand =rep("rand", nqRand)
names(grpRand) = paste("rand_", 1:nqRand, sep='')
sgrp = append(sgrp, grpRand)

# heatmap classification result
sc_hmClass(crParkall, sgrp, max=5000, isBig=TRUE, cCol=F, font=8)
```


```{r}
# This classifies a cell with  the catgory with the highest classification score or higher than a classification score threshold of your choosing.
# The annotation result can be found in a column named category in the query sample table.

stPark <- get_cate(classRes = crParkall, sampTab = stPark, dLevel = "description1", sid = "sample_name", nrand = nqRand)
```


# cross species classification
```{r}
stQuery = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/stDat_beads_mar22.rda")
expQuery = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/6k_beadpurfied_raw.rda") # use Matrix if RAM low

stTM = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/sampTab_TM_053018.rda")
expTMraw = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/expMatrix_TM_Raw_Oct_12_2018.rda") # reload training
```

```{r}
oTab = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/human_mouse_genes_Jul_24_2018.rda")
aa = csRenameOrth(expQuery, expTMraw, oTab)
expQueryOrth = aa[['expQuery']]
expTrainOrth = aa[['expTrain']]
```
```{r}
cts = c("B cell",  "cardiac muscle cell", "endothelial cell", "erythroblast", "granulocyte", "hematopoietic precursor cell", "late pro-B cell", "limb_mesenchymal", "macrophage", "mammary_basal_cell", "monocyte", "natural killer cell", "T cell", "trachea_epithelial", "trachea_mesenchymal")

stTM2 = filter(stTM, newAnn %in% cts)
stTM2 = droplevels(stTM2)
rownames(stTM2) = as.vector(stTM2$cell) # filter strips rownames

expTMraw2 = expTrainOrth[,rownames(stTM2)]
stList = splitCommon(stTM2, ncells=100, dLevel="newAnn")
stTrain = stList[[1]]
expTrain = expTMraw2[,rownames(stTrain)]

system.time(class_info2<-scn_train(stTrain = stTrain, expTrain = expTrain, nTopGenes = 10, nRand = 70, nTrees = 1000, nTopGenePairs = 25, dLevel = "newAnn", colName_samp = "cell"))
 
```
```{r}
#validate data
stTestList = splitCommon(stList[[2]], ncells=100, dLevel="newAnn") 
stTest = stTestList[[1]]
expTest = expTMraw2[,rownames(stTest)]

#predict
system.time(classRes_val_all2 <- scn_predict(class_info2[['cnProc']], expTest, nrand = 50))
```

```{r}
stQuery$description = as.character(stQuery$description)
stQuery[which(stQuery$description == "NK cell"), "description"] = "natural killer cell"

nqRand = 50
system.time(crHS <- scn_predict(class_info2[['cnProc']], expQueryOrth, nrand=nqRand))
```

```{r}
stQuery = utils_loadObject("/liulab/asahu/data/single_cell/singleCellNet/stList_Park.rda")
```

```{r}
cts = c("B cell",  "cardiac muscle cell", "endothelial cell", "erythroblast", "granulocyte", "hematopoietic precursor cell", "late pro-B cell", "limb_mesenchymal", "macrophage", "mammary_basal_cell", "monocyte", "natural killer cell", "T cell", "trachea_epithelial", "trachea_mesenchymal", "alveolar macrophage", "erythrocyte", "hepatocyte", "keratinocyte")
```

